### ISSUE TITLE
migrating code from biocViews

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/biocViews#10]
As discussed in one of our meetings, we need to move code that works with `NEWS` files to another package, perhaps `ReleaseLaunch` or a new package?

FWIW I have also worked on compiling `NEWS` at https://github.com/LiNk-NY/newsfeed 

@hpages @lshep 
What other functionality should we move out of `biocViews`?

**Comment by hpages** [comment]
Moving the code that handles `NEWS` files to the **ReleaseLaunch** package seems sensible. I'd suggest this issue focuses on that code. Separated issues can be opened later if additional code needs to be moved. Thanks @LiNk-NY

**Comment by hpages** [comment]
@LiNk-NY I still see a bunch of NEWS related functions in **biocViews** (`extractNEWS`, `getPackageNEWS`, `printNEWS`, `getNEWSFromFile`). They should be deprecated in favor of the things that are now in **ReleaseLaunch**.

Also it seems that you've migrated more things than just the NEWS related stuff to **ReleaseLaunch**. Please make sure to deprecate all the things in **biocViews** that are now in **ReleaseLaunch**. Thanks!
