### ISSUE TITLE
Make getNEWSFromFile or extractNEWS more robust

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/biocViews#3]
If `extractNEWS` encounters a (very) bad news file then it stops completely. The issue seems to be located in `getNEWSFromFile`. Herve's example:

```
biocViews:::getNEWSFromFile("path/to/dittoSeq/", "test.txt", output="text")
Warning: ./inst/NEWS.Rd:6: All text must be in a section
Warning: ./inst/NEWS.Rd:7: All text must be in a section
Error in switch(tag, USERMACRO = , `\\newcommand` = , `\\renewcommand` = ,  : 
  EXPR must be a length 1 vector
In addition: Warning messages:
1: In parse_Rd(file, macros = macros) :
  bad markup (extra space?) at NEWS.Rd:5:24
2: In parse_Rd(file, macros = macros) :
  ./inst/NEWS.Rd:5: unexpected macro '\itemize'
```

See dittoSeq commit 63c7d670f362611eb8f2af6f4857a92b46690cb7.

**Comment by hpages** [comment]
Thanks Jennifer. I committed a fix: commit 277520f600fe0f09185bf3febb0344eefa918baa, **biocViews** 1.61.3.

To deploy on nebbiolo2 you need to install this new version of **biocViews** for the instance of R used by the biocpush user (the biocpush user uses its own R instance that is different from the R instance used by the daily builds and SPB). You should be able to do so with:
```
cd ~/pkgs_to_install/biocViews
git pull
R-4.1 CMD INSTALL .
```
Thanks!
